### ISSUE TITLE
Update documentation repo for OSDI implementation

### ISSUE THREAD

**Issue by AaronSofaer** [Ragtagteam/cta-aggregator#23]

**Comment by AaronSofaer** [comment]
This work should incorporate the naming convention changes, inasmuch as they're relevant, from this PR: https://github.com/Ragtagteam/cta-aggregator-docs/pull/1/files

and they should also incorporate in some form the call scripts work from this PR, in an OSDI-y way: https://github.com/Ragtagteam/cta-aggregator-docs/pull/2/files , which hopefully is now in the data models?

**Comment by spikex** [comment]
Understood, I'll work from those PR.
