### ISSUE TITLE
Web scrapers for initial couple of sites

### ISSUE THREAD

**Issue by AaronSofaer** [Ragtagteam/cta-aggregator#26]
We need a scraper capable of importing data from 5calls and/or Emily's list.

This will probably be a rails app that scrapes sites, coerces data into a hash and then uses the CTAA gem to POST data to the CTAA API.

(this needs to be assigned to Chris Brickey)

**Comment by chrisbrickey** [comment]
On it!

**Comment by jkriss** [comment]
Do we know which sources we want to have in place for v1?

**Comment by bnd5k** [comment]
@chrisbrickey has done prelimary work on scraping Emily's list and 5Calls.
Any others we should include, @AaronSofaer ?

**Comment by AaronSofaer** [comment]
I don't have strong preferences. I'd like to see at least one primarily calls-driven source and at least one primarily events-driven source, but more importantly I want a process for easily adding more, because we should expect to scale up fast as soon as we know we're on the right track.

**Comment by jkriss** [comment]
A bit of an aside, but do we have permission from both of those organizations?

**Comment by AaronSofaer** [comment]
We are not seeking permission from organizations at this time. We may in the future seek active cooperation (e.g., "do you want to expose a machine-readable endpoint to us" kind of stuff) but never permission.

**Comment by jkriss** [comment]
Why never? Sure, if we're obeying robots.txt, then arguably we're within our rights, but wouldn't it make for a smoother launch and better publicity if we at least started with organizations that actually wanted to work with us?

**Comment by AaronSofaer** [comment]
Discussed in Slack. For now let's focus on deciding on a framework and process for adding sites.

**Comment by AaronSofaer** [comment]
The framework for this has been added by @bnd5k as the CTA Scraper app in RagtagOpen. We still need to actually scrape in the first couple sites.
