### ISSUE TITLE
Documentation for "zero to you can now display a feed in your website" in docs repo

### ISSUE THREAD

**Issue by AaronSofaer** [Ragtagteam/cta-aggregator#28]

**Comment by jkriss** [comment]
Catching up on the docs a bit. Am I right to think that, in the simple case, this is one authenticated REST call?

If so, and if we have CORS enabled, then the actions could be loaded client side, which would be ideal.

It'd probably be valuable to make a small, read only javascript client that supports paging and searching, assuming those are available in the underlying API. This would likely be the easiest integration path for most people.

**Comment by bnd5k** [comment]
Reads from the API don't require authentication.  So you can get a list of CTAs or view an individual one without registering for an API key.

**Comment by jkriss** [comment]
Awesome. Can we add CORS headers for those read endpoints, too, so that they can be requested from javascript on any domain?

**Comment by bnd5k** [comment]
For sure.  PRs are always welcome. :)

**Comment by AaronSofaer** [comment]
Note that in the future reads *may* require authentication, so let's make sure we don't build ourselves into a corner.

**Comment by jkriss** [comment]
We should talk about the how, when, and why for that a bit more to better determine the painting-into-a-corner risk. Keeping it unauthenticated would make adoption significantly easier.

If we’re worried about who can use it on their site, we could lock that down by only allowing it to run on certain domains, but still have the requests be unauthenticated (which would allow for purely client-side integration).

**Comment by AaronSofaer** [comment]
My concerns are not so much who can run it on their site as they are about rate-limiting.

**Comment by jkriss** [comment]
Ah, cool. We should be able to rate limit by IP address (which in this case would be the end user’s IP, not the server) or by referrer, which would be the embedding page url (could rate limit by full url or domain).

**Comment by AaronSofaer** [comment]
👍

**Comment by jkriss** [comment]
Added a README and GitHub Pages site to https://github.com/Ragtagteam/cta-aggregator-js, and made it public.
