### ISSUE TITLE
Cucumber -> rspec

### ISSUE THREAD

**Issue by AaronSofaer** [Ragtagteam/cta-aggregator#29]
We used cucumber to manage integration testing.  But in the interest of keeping the code base as lean as possible, we've decided to rely on rspec for our integration tests.

Note: there's not point to changing the existing cukes over to rspec.  We're just going to use RSpec when we start integrating the OSDI data modelling.

**Comment by UnderpantsGnome** [comment]
This is happening as part of the OSDI feature branch

**Comment by AaronSofaer** [comment]
Closed as incidentally fixed per #34 , reopen if I'm wrong about that :)
