### ISSUE TITLE
Docker setup doesn't work on Mac OSX Sierra unless a line is removed

### ISSUE THREAD

**Issue by jillh510** [Ragtagteam/cta-aggregator#42]
Setting up a local env using the "Setup (Docker)" instructions in the README, <docker-compose run web bin/setup> would fail with 
[!] There was an error parsing `Gemfile`: No such file or directory @ rb_sysopen - .ruby-version. Bundler cannot continue.

  #  from /cta-aggregator/Gemfile:3
  #  -------------------------------------------
  #  
 >  ruby File.read('.ruby-version').chomp
  #  
  #  -------------------------------------------

I just removed that line from the Gemfile, and things seemed to be fine.

Mac OSX, 10.12.6
ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]

**Comment by jkriss** [comment]
The Dockerfile should include the `.ruby-version` file. Pull req incoming...
