### ISSUE TITLE
Work with OSDI to implement call scripts for advocacy campaigns

### ISSUE THREAD

**Issue by AaronSofaer** [Ragtagteam/cta-aggregator#62]
Call scripts seem like a cool thing to add. See also: https://github.com/Ragtagteam/cta-aggregator-docs/pull/2/files

**Comment by bnd5k** [comment]
The call script resource is now an attribute of Advocacy Campaigns in the CTAA API.   

We originally had a dedicated table for this info, but when we moved over to the OSDI data model, we made it part of the Advocacy Campaign model.   In this OSDI spec, the call script is referred to as the "template." https://opensupporter.github.io/osdi-docs/advocacy_campaigns.html has

**Comment by AaronSofaer** [comment]
Derp. Thanks for pointing that out.
