### ISSUE TITLE
Rename /authorize

### ISSUE THREAD

**Issue by AaronSofaer** [Ragtagteam/cta-aggregator#70]
to /authentications?

"Any objection to changing the name of the  `/authorize` endpoint?  It seems wrong that an endpoint named "authorize" is responsible for authentication and doesn't much to do with authorization.  I'd like to at least get a noun as the resource name instead of a verb, just to stick to RESTful conventions.  Maybe ` /authentications`?"

**Comment by bnd5k** [comment]
PR: https://github.com/Ragtagteam/cta-aggregator/pull/73
